[tox]
envlist = py310sp111, py310sp115, py314sp116
isolated_build = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}/tests
commands =
    python -m unittest discover -s tests -t . -p "test_*.py"

[testenv:py310sp111]
basepython = python3.10
deps =
    scipy==1.11.0

[testenv:py314sp116]
basepython = python3.14
deps =
    scipy==1.16.1

[testenv:py310sp115]
basepython = python3.10
deps =
    scipy==1.15.0
