""".. _dyad_api:

==================
Dyad (:mod:`dyad`)
==================

.. currentmodule:: dyad

.. include:: ../../../README.md
   :end-before: **Website:**

Notes
-----

The geometry of an orbit is shown in Figures :numref:`orbit` and
:numref:`orientation`. That orbit is an ellipse with *semimajor axis*,
:math:`a` and *eccentricity*, :math:`e`. The body's phase is described
by its *true anomaly*, :math:`\theta`, which is the angle subtended
by the body and the primary vertex (i.e. the point of perigee) at the
primary focus, :math:`F_{1}`. The *perifocal coordinate system* has
origin :math:`F_{1}` and orthogonal basis :math:`(\mathbf{e}_{p},
\mathbf{e}_{q}, \mathbf{e}_{w})` such that :math:`\mathbf{e}_{p}` is
parallel with the latus rectum, :math:`\mathbf{e}_{q}` is parallel
with the major axis, and :math:`\mathbf{e}_{w}` is parallel with the
body's angular momentum. If the observer's frame is coordinatized by
the orthogonal basis :math:`(\mathbf{e}_{x}, \mathbf{e}_{y},
\mathbf{e}_{z})` then the perifocal system is a rotation of the
observer's system defined by Euler angles :math:`\Omega`, :math:`i`,
and :math:`\omega` (being the *longitude of the ascending node*, the
*inclination*, and the *argument of pericentre*).

.. _orbit:
.. figure:: ../figures/elliptical_orbit.jpg
   :figwidth: 75%
   :align: center

   The orbit of a bound body in a gravitational central potential. The
   pericentral frame has coordinates :math:`X` and :math:`Y` while the
   perifocal frame has coordinates :math:`p` and :math:`q`.

.. _orientation:
.. figure:: ../figures/orbital_euler_angles.jpg
   :figwidth: 75%
   :align: center

   The orientation of the perifocal coordinates system with respect to
   the coordinate system of the observer is described by the Euler
   angles :math:`\Omega`, :math:`i`, and :math:`\omega`. The unit
   vector :math:`\mathbf{e}_{N}` is parallel with the *line of nodes*
   (i.e. the straight line passing through :math:`F_{1}` and the
   *ascending node*, being the point at which the orbit and the
   observer's plane of reference intersect).

The geometry of a binary system's component orbits is shown in Figure
:numref:`twobodysystem`. Both bodies move on elliptical orbits with
primary foci coincident with the system's centre of mass (COM)
frame. The more-massive (resp. less-massive) body moves as if in a
central potential generated by a mass of :math:`m_{2}^{3}/(m_{1} +
m_{2})^{2}` (resp. :math:`m_{1}^{3}/(m_{1} + m_{2})^{2}`). Its orbit
is described by its semimajor axis, :math:`a_{1}`
(resp. :math:`a_{2}`), and eccentricity, :math:`e_{1}`
(resp. :math:`e_{2}`). Its orientation is defined by the longitude of
its ascending node, :math:`\Omega_{1}` (resp. :math:`\Omega_{2}`),
inclination, :math:`i_{1}` (resp. :math:`i_{2}`), and argument of
pericentre, :math:`\omega_{1}` (resp. :math:`\omega_{2}`). The phase
of the more-massive (resp. less-massive) body is described by its true
anomaly, :math:`\theta_{1}` (resp. :math:`\theta_{2})`. It is the case
that :math:`a_{2} = a_{1}/q`, :math:`e_{2} = e_{1}`. :math:`\Omega_{2}
= \Omega_{1}`, :math:`i_{2} = i_{1}`, :math:`\omega_{2} = \omega_{1} +
\pi` and :math:`\theta_{1} = \theta_{2}`.

.. _twobodysystem:
.. figure:: ../figures/twobody_system.jpg
   :figwidth: 75%
   :align: center

   The orbits of the components of a two-body system.

Classes
-------
.. autosummary::
   :toctree: generated/

   Orbit
   TwoBody

Functions
---------
.. autosummary::
   :toctree: generated/

   semimajor_axis_from_period
   period_from_semimajor_axis
   true_anomaly_from_mean_anomaly
   true_anomaly_from_eccentric_anomaly
   mean_anomaly_from_eccentric_anomaly
   mean_anomaly_from_true_anomaly
   eccentric_anomaly_from_true_anomaly
   eccentric_anomaly_from_mean_anomaly
   delaunay_elements_from_orbital_elements
   orbital_elements_from_delaunay_elements
   modified_delaunay_elements_from_orbital_elements
   orbital_elements_from_modified_delaunay_elements

"""
from . import _constants

from ._core import *
from . import stats
